<?=$this->doctype('HTML5')?>
<html xmlns="http://www.w3.org/1999/xhtml" lang="pt-br">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    </head>
    
<center><h1>Impressão Cadastro de Papel</h1></center>

<b>Cargo:</b> <?=$this->dadosPapel['desc_cargo'];?><br>
<b>Data de Inclusão:</b> <?=$this->dadosPapel['dt_inclusao'];?><br>
<b>Data de Alteração:</b> <?=$this->dadosPapel['dt_alteracao'];?><br>
<b>Status:</b> <?=$this->dadosPapel['flg_status_papel'];?><br>

</html>
